/* 
 * Mentoring API
 *
 * No descripton provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;

namespace IO.Swagger.Model
{
    /// <summary>
    /// Products
    /// </summary>
    [DataContract]
    public partial class Products :  IEquatable<Products>
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="Products" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected Products() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="Products" /> class.
        /// </summary>
        /// <param name="ProductId">ProductId.</param>
        /// <param name="ProductName">ProductName (required).</param>
        /// <param name="SupplierId">SupplierId.</param>
        /// <param name="CategoryId">CategoryId.</param>
        /// <param name="QuantityPerUnit">QuantityPerUnit.</param>
        /// <param name="UnitPrice">UnitPrice.</param>
        /// <param name="UnitsInStock">UnitsInStock.</param>
        /// <param name="UnitsOnOrder">UnitsOnOrder.</param>
        /// <param name="ReorderLevel">ReorderLevel.</param>
        /// <param name="Discontinued">Discontinued.</param>
        /// <param name="Category">Category.</param>
        /// <param name="Supplier">Supplier.</param>
        /// <param name="OrderDetails">OrderDetails.</param>
        public Products(int? ProductId = null, string ProductName = null, int? SupplierId = null, int? CategoryId = null, string QuantityPerUnit = null, double? UnitPrice = null, int? UnitsInStock = null, int? UnitsOnOrder = null, int? ReorderLevel = null, bool? Discontinued = null, Categories Category = null, Suppliers Supplier = null, List<OrderDetails> OrderDetails = null)
        {
            // to ensure "ProductName" is required (not null)
            if (ProductName == null)
            {
                throw new InvalidDataException("ProductName is a required property for Products and cannot be null");
            }
            else
            {
                this.ProductName = ProductName;
            }
            this.ProductId = ProductId;
            this.SupplierId = SupplierId;
            this.CategoryId = CategoryId;
            this.QuantityPerUnit = QuantityPerUnit;
            this.UnitPrice = UnitPrice;
            this.UnitsInStock = UnitsInStock;
            this.UnitsOnOrder = UnitsOnOrder;
            this.ReorderLevel = ReorderLevel;
            this.Discontinued = Discontinued;
            this.Category = Category;
            this.Supplier = Supplier;
            this.OrderDetails = OrderDetails;
        }
        
        /// <summary>
        /// Gets or Sets ProductId
        /// </summary>
        [DataMember(Name="productId", EmitDefaultValue=false)]
        public int? ProductId { get; set; }
        /// <summary>
        /// Gets or Sets ProductName
        /// </summary>
        [DataMember(Name="productName", EmitDefaultValue=false)]
        public string ProductName { get; set; }
        /// <summary>
        /// Gets or Sets SupplierId
        /// </summary>
        [DataMember(Name="supplierId", EmitDefaultValue=false)]
        public int? SupplierId { get; set; }
        /// <summary>
        /// Gets or Sets CategoryId
        /// </summary>
        [DataMember(Name="categoryId", EmitDefaultValue=false)]
        public int? CategoryId { get; set; }
        /// <summary>
        /// Gets or Sets QuantityPerUnit
        /// </summary>
        [DataMember(Name="quantityPerUnit", EmitDefaultValue=false)]
        public string QuantityPerUnit { get; set; }
        /// <summary>
        /// Gets or Sets UnitPrice
        /// </summary>
        [DataMember(Name="unitPrice", EmitDefaultValue=false)]
        public double? UnitPrice { get; set; }
        /// <summary>
        /// Gets or Sets UnitsInStock
        /// </summary>
        [DataMember(Name="unitsInStock", EmitDefaultValue=false)]
        public int? UnitsInStock { get; set; }
        /// <summary>
        /// Gets or Sets UnitsOnOrder
        /// </summary>
        [DataMember(Name="unitsOnOrder", EmitDefaultValue=false)]
        public int? UnitsOnOrder { get; set; }
        /// <summary>
        /// Gets or Sets ReorderLevel
        /// </summary>
        [DataMember(Name="reorderLevel", EmitDefaultValue=false)]
        public int? ReorderLevel { get; set; }
        /// <summary>
        /// Gets or Sets Discontinued
        /// </summary>
        [DataMember(Name="discontinued", EmitDefaultValue=false)]
        public bool? Discontinued { get; set; }
        /// <summary>
        /// Gets or Sets Category
        /// </summary>
        [DataMember(Name="category", EmitDefaultValue=false)]
        public Categories Category { get; set; }
        /// <summary>
        /// Gets or Sets Supplier
        /// </summary>
        [DataMember(Name="supplier", EmitDefaultValue=false)]
        public Suppliers Supplier { get; set; }
        /// <summary>
        /// Gets or Sets OrderDetails
        /// </summary>
        [DataMember(Name="orderDetails", EmitDefaultValue=false)]
        public List<OrderDetails> OrderDetails { get; set; }
        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class Products {\n");
            sb.Append("  ProductId: ").Append(ProductId).Append("\n");
            sb.Append("  ProductName: ").Append(ProductName).Append("\n");
            sb.Append("  SupplierId: ").Append(SupplierId).Append("\n");
            sb.Append("  CategoryId: ").Append(CategoryId).Append("\n");
            sb.Append("  QuantityPerUnit: ").Append(QuantityPerUnit).Append("\n");
            sb.Append("  UnitPrice: ").Append(UnitPrice).Append("\n");
            sb.Append("  UnitsInStock: ").Append(UnitsInStock).Append("\n");
            sb.Append("  UnitsOnOrder: ").Append(UnitsOnOrder).Append("\n");
            sb.Append("  ReorderLevel: ").Append(ReorderLevel).Append("\n");
            sb.Append("  Discontinued: ").Append(Discontinued).Append("\n");
            sb.Append("  Category: ").Append(Category).Append("\n");
            sb.Append("  Supplier: ").Append(Supplier).Append("\n");
            sb.Append("  OrderDetails: ").Append(OrderDetails).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            // credit: http://stackoverflow.com/a/10454552/677735
            return this.Equals(obj as Products);
        }

        /// <summary>
        /// Returns true if Products instances are equal
        /// </summary>
        /// <param name="other">Instance of Products to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(Products other)
        {
            // credit: http://stackoverflow.com/a/10454552/677735
            if (other == null)
                return false;

            return 
                (
                    this.ProductId == other.ProductId ||
                    this.ProductId != null &&
                    this.ProductId.Equals(other.ProductId)
                ) && 
                (
                    this.ProductName == other.ProductName ||
                    this.ProductName != null &&
                    this.ProductName.Equals(other.ProductName)
                ) && 
                (
                    this.SupplierId == other.SupplierId ||
                    this.SupplierId != null &&
                    this.SupplierId.Equals(other.SupplierId)
                ) && 
                (
                    this.CategoryId == other.CategoryId ||
                    this.CategoryId != null &&
                    this.CategoryId.Equals(other.CategoryId)
                ) && 
                (
                    this.QuantityPerUnit == other.QuantityPerUnit ||
                    this.QuantityPerUnit != null &&
                    this.QuantityPerUnit.Equals(other.QuantityPerUnit)
                ) && 
                (
                    this.UnitPrice == other.UnitPrice ||
                    this.UnitPrice != null &&
                    this.UnitPrice.Equals(other.UnitPrice)
                ) && 
                (
                    this.UnitsInStock == other.UnitsInStock ||
                    this.UnitsInStock != null &&
                    this.UnitsInStock.Equals(other.UnitsInStock)
                ) && 
                (
                    this.UnitsOnOrder == other.UnitsOnOrder ||
                    this.UnitsOnOrder != null &&
                    this.UnitsOnOrder.Equals(other.UnitsOnOrder)
                ) && 
                (
                    this.ReorderLevel == other.ReorderLevel ||
                    this.ReorderLevel != null &&
                    this.ReorderLevel.Equals(other.ReorderLevel)
                ) && 
                (
                    this.Discontinued == other.Discontinued ||
                    this.Discontinued != null &&
                    this.Discontinued.Equals(other.Discontinued)
                ) && 
                (
                    this.Category == other.Category ||
                    this.Category != null &&
                    this.Category.Equals(other.Category)
                ) && 
                (
                    this.Supplier == other.Supplier ||
                    this.Supplier != null &&
                    this.Supplier.Equals(other.Supplier)
                ) && 
                (
                    this.OrderDetails == other.OrderDetails ||
                    this.OrderDetails != null &&
                    this.OrderDetails.SequenceEqual(other.OrderDetails)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            // credit: http://stackoverflow.com/a/263416/677735
            unchecked // Overflow is fine, just wrap
            {
                int hash = 41;
                // Suitable nullity checks etc, of course :)
                if (this.ProductId != null)
                    hash = hash * 59 + this.ProductId.GetHashCode();
                if (this.ProductName != null)
                    hash = hash * 59 + this.ProductName.GetHashCode();
                if (this.SupplierId != null)
                    hash = hash * 59 + this.SupplierId.GetHashCode();
                if (this.CategoryId != null)
                    hash = hash * 59 + this.CategoryId.GetHashCode();
                if (this.QuantityPerUnit != null)
                    hash = hash * 59 + this.QuantityPerUnit.GetHashCode();
                if (this.UnitPrice != null)
                    hash = hash * 59 + this.UnitPrice.GetHashCode();
                if (this.UnitsInStock != null)
                    hash = hash * 59 + this.UnitsInStock.GetHashCode();
                if (this.UnitsOnOrder != null)
                    hash = hash * 59 + this.UnitsOnOrder.GetHashCode();
                if (this.ReorderLevel != null)
                    hash = hash * 59 + this.ReorderLevel.GetHashCode();
                if (this.Discontinued != null)
                    hash = hash * 59 + this.Discontinued.GetHashCode();
                if (this.Category != null)
                    hash = hash * 59 + this.Category.GetHashCode();
                if (this.Supplier != null)
                    hash = hash * 59 + this.Supplier.GetHashCode();
                if (this.OrderDetails != null)
                    hash = hash * 59 + this.OrderDetails.GetHashCode();
                return hash;
            }
        }
    }

}
