/* 
 * Mentoring API
 *
 * No descripton provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;

namespace IO.Swagger.Model
{
    /// <summary>
    /// Territories
    /// </summary>
    [DataContract]
    public partial class Territories :  IEquatable<Territories>
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="Territories" /> class.
        /// </summary>
        /// <param name="TerritoryId">TerritoryId.</param>
        /// <param name="TerritoryDescription">TerritoryDescription.</param>
        /// <param name="RegionId">RegionId.</param>
        /// <param name="Region">Region.</param>
        /// <param name="EmployeeTerritories">EmployeeTerritories.</param>
        public Territories(string TerritoryId = null, string TerritoryDescription = null, int? RegionId = null, Region Region = null, List<EmployeeTerritories> EmployeeTerritories = null)
        {
            this.TerritoryId = TerritoryId;
            this.TerritoryDescription = TerritoryDescription;
            this.RegionId = RegionId;
            this.Region = Region;
            this.EmployeeTerritories = EmployeeTerritories;
        }
        
        /// <summary>
        /// Gets or Sets TerritoryId
        /// </summary>
        [DataMember(Name="territoryId", EmitDefaultValue=false)]
        public string TerritoryId { get; set; }
        /// <summary>
        /// Gets or Sets TerritoryDescription
        /// </summary>
        [DataMember(Name="territoryDescription", EmitDefaultValue=false)]
        public string TerritoryDescription { get; set; }
        /// <summary>
        /// Gets or Sets RegionId
        /// </summary>
        [DataMember(Name="regionId", EmitDefaultValue=false)]
        public int? RegionId { get; set; }
        /// <summary>
        /// Gets or Sets Region
        /// </summary>
        [DataMember(Name="region", EmitDefaultValue=false)]
        public Region Region { get; set; }
        /// <summary>
        /// Gets or Sets EmployeeTerritories
        /// </summary>
        [DataMember(Name="employeeTerritories", EmitDefaultValue=false)]
        public List<EmployeeTerritories> EmployeeTerritories { get; set; }
        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class Territories {\n");
            sb.Append("  TerritoryId: ").Append(TerritoryId).Append("\n");
            sb.Append("  TerritoryDescription: ").Append(TerritoryDescription).Append("\n");
            sb.Append("  RegionId: ").Append(RegionId).Append("\n");
            sb.Append("  Region: ").Append(Region).Append("\n");
            sb.Append("  EmployeeTerritories: ").Append(EmployeeTerritories).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            // credit: http://stackoverflow.com/a/10454552/677735
            return this.Equals(obj as Territories);
        }

        /// <summary>
        /// Returns true if Territories instances are equal
        /// </summary>
        /// <param name="other">Instance of Territories to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(Territories other)
        {
            // credit: http://stackoverflow.com/a/10454552/677735
            if (other == null)
                return false;

            return 
                (
                    this.TerritoryId == other.TerritoryId ||
                    this.TerritoryId != null &&
                    this.TerritoryId.Equals(other.TerritoryId)
                ) && 
                (
                    this.TerritoryDescription == other.TerritoryDescription ||
                    this.TerritoryDescription != null &&
                    this.TerritoryDescription.Equals(other.TerritoryDescription)
                ) && 
                (
                    this.RegionId == other.RegionId ||
                    this.RegionId != null &&
                    this.RegionId.Equals(other.RegionId)
                ) && 
                (
                    this.Region == other.Region ||
                    this.Region != null &&
                    this.Region.Equals(other.Region)
                ) && 
                (
                    this.EmployeeTerritories == other.EmployeeTerritories ||
                    this.EmployeeTerritories != null &&
                    this.EmployeeTerritories.SequenceEqual(other.EmployeeTerritories)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            // credit: http://stackoverflow.com/a/263416/677735
            unchecked // Overflow is fine, just wrap
            {
                int hash = 41;
                // Suitable nullity checks etc, of course :)
                if (this.TerritoryId != null)
                    hash = hash * 59 + this.TerritoryId.GetHashCode();
                if (this.TerritoryDescription != null)
                    hash = hash * 59 + this.TerritoryDescription.GetHashCode();
                if (this.RegionId != null)
                    hash = hash * 59 + this.RegionId.GetHashCode();
                if (this.Region != null)
                    hash = hash * 59 + this.Region.GetHashCode();
                if (this.EmployeeTerritories != null)
                    hash = hash * 59 + this.EmployeeTerritories.GetHashCode();
                return hash;
            }
        }
    }

}
